// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"
#include "Vtop___024unit.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_hft_pipeline_top);
    __Vhier.remove(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_demux);
    __Vhier.remove(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_filter);
    __Vhier.remove(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_framer);
    __Vhier.remove(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_index_arb);
    __Vhier.remove(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_order_lookup);
    __Vhier.remove(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_tob);
    __Vhier.remove(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_tx);
    __Vhier.remove(&__Vscope_hft_pipeline_top__u_order_lookup, &__Vscope_hft_pipeline_top__u_order_lookup__u_order_table);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-10);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top.configure(this, name(), "hft_pipeline_top", "hft_pipeline_top", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_hft_pipeline_top__u_demux.configure(this, name(), "hft_pipeline_top.u_demux", "u_demux", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_hft_pipeline_top__u_filter.configure(this, name(), "hft_pipeline_top.u_filter", "u_filter", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_hft_pipeline_top__u_framer.configure(this, name(), "hft_pipeline_top.u_framer", "u_framer", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_hft_pipeline_top__u_index_arb.configure(this, name(), "hft_pipeline_top.u_index_arb", "u_index_arb", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_hft_pipeline_top__u_index_arb__unnamedblk1.configure(this, name(), "hft_pipeline_top.u_index_arb.unnamedblk1", "unnamedblk1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_index_arb__unnamedblk2.configure(this, name(), "hft_pipeline_top.u_index_arb.unnamedblk2", "unnamedblk2", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_order_lookup.configure(this, name(), "hft_pipeline_top.u_order_lookup", "u_order_lookup", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.configure(this, name(), "hft_pipeline_top.u_order_lookup.u_order_table", "u_order_table", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__0__KET__.configure(this, name(), "hft_pipeline_top.u_order_lookup.u_order_table.gen_bram[0]", "gen_bram[0]", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__1__KET__.configure(this, name(), "hft_pipeline_top.u_order_lookup.u_order_table.gen_bram[1]", "gen_bram[1]", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__2__KET__.configure(this, name(), "hft_pipeline_top.u_order_lookup.u_order_table.gen_bram[2]", "gen_bram[2]", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__3__KET__.configure(this, name(), "hft_pipeline_top.u_order_lookup.u_order_table.gen_bram[3]", "gen_bram[3]", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk3.configure(this, name(), "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk3", "unnamedblk3", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk4.configure(this, name(), "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk4", "unnamedblk4", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk5.configure(this, name(), "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk5", "unnamedblk5", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk6.configure(this, name(), "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk6", "unnamedblk6", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk7.configure(this, name(), "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk7", "unnamedblk7", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk8.configure(this, name(), "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk8", "unnamedblk8", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk9.configure(this, name(), "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk9", "unnamedblk9", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob.configure(this, name(), "hft_pipeline_top.u_tob", "u_tob", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk1.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk1", "unnamedblk1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk10.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk10", "unnamedblk10", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk10__unnamedblk11.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk10.unnamedblk11", "unnamedblk11", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk12.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk12", "unnamedblk12", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk13.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk13", "unnamedblk13", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk2.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk2", "unnamedblk2", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk3.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk3", "unnamedblk3", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk3__unnamedblk4.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk3.unnamedblk4", "unnamedblk4", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk5.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk5", "unnamedblk5", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk6.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk6", "unnamedblk6", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk7.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk7", "unnamedblk7", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk8.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk8", "unnamedblk8", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tob__unnamedblk8__unnamedblk9.configure(this, name(), "hft_pipeline_top.u_tob.unnamedblk8.unnamedblk9", "unnamedblk9", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_hft_pipeline_top__u_tx.configure(this, name(), "hft_pipeline_top.u_tx", "u_tx", -9, VerilatedScope::SCOPE_MODULE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_hft_pipeline_top);
    __Vhier.add(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_demux);
    __Vhier.add(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_filter);
    __Vhier.add(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_framer);
    __Vhier.add(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_index_arb);
    __Vhier.add(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_order_lookup);
    __Vhier.add(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_tob);
    __Vhier.add(&__Vscope_hft_pipeline_top, &__Vscope_hft_pipeline_top__u_tx);
    __Vhier.add(&__Vscope_hft_pipeline_top__u_order_lookup, &__Vscope_hft_pipeline_top__u_order_lookup__u_order_table);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOP.clk), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"computed_index", &(TOP.computed_index), false, VLVT_UINT64,VLVD_OUT|VLVF_PUB_RW,1 ,63,0);
        __Vscope_TOP.varInsert(__Vfinal,"net_position", &(TOP.net_position), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"ol_ready", &(TOP.ol_ready), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"order_count", &(TOP.order_count), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"pkt_sent", &(TOP.pkt_sent), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst_n", &(TOP.rst_n), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"rx_axis_tdata", &(TOP.rx_axis_tdata), false, VLVT_UINT64,VLVD_IN|VLVF_PUB_RW,1 ,63,0);
        __Vscope_TOP.varInsert(__Vfinal,"rx_axis_tkeep", &(TOP.rx_axis_tkeep), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"rx_axis_tlast", &(TOP.rx_axis_tlast), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"rx_axis_tready", &(TOP.rx_axis_tready), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"rx_axis_tvalid", &(TOP.rx_axis_tvalid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"threshold", &(TOP.threshold), false, VLVT_UINT64,VLVD_IN|VLVF_PUB_RW,1 ,63,0);
        __Vscope_TOP.varInsert(__Vfinal,"tob_snapshot", &(TOP.tob_snapshot), false, VLVT_WDATA,VLVD_OUT|VLVF_PUB_RW,1 ,137,0);
        __Vscope_TOP.varInsert(__Vfinal,"trade_signal", &(TOP.trade_signal), false, VLVT_WDATA,VLVD_OUT|VLVF_PUB_RW,1 ,161,0);
        __Vscope_TOP.varInsert(__Vfinal,"tx_axis_tdata", &(TOP.tx_axis_tdata), false, VLVT_UINT64,VLVD_OUT|VLVF_PUB_RW,1 ,63,0);
        __Vscope_TOP.varInsert(__Vfinal,"tx_axis_tkeep", &(TOP.tx_axis_tkeep), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"tx_axis_tlast", &(TOP.tx_axis_tlast), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"tx_axis_tready", &(TOP.tx_axis_tready), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"tx_axis_tvalid", &(TOP.tx_axis_tvalid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"tx_enable", &(TOP.tx_enable), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"wt_wr_addr", &(TOP.wt_wr_addr), false, VLVT_UINT16,VLVD_IN|VLVF_PUB_RW,1 ,8,0);
        __Vscope_TOP.varInsert(__Vfinal,"wt_wr_data", &(TOP.wt_wr_data), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"wt_wr_en", &(TOP.wt_wr_en), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"COOLDOWN_CYC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__COOLDOWN_CYC))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"DST_IP", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__DST_IP))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"DST_MAC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__DST_MAC))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"DST_PORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__DST_PORT))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"FILTER_PORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__FILTER_PORT))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"HEADER_BYTES", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__HEADER_BYTES))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"HT_MAX_CHAIN", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__HT_MAX_CHAIN))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"HT_N_WAYS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__HT_N_WAYS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"HT_TBL_ENTRIES", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__HT_TBL_ENTRIES))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"IDX_SYM", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__IDX_SYM))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,8,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"IDX_SYM_ID", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__IDX_SYM_ID))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"MAX_POS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__MAX_POS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"N_COMPONENTS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__N_COMPONENTS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"ORDER_QTY", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__ORDER_QTY))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"PRICE_OFFSET", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__PRICE_OFFSET))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"SRC_IP", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__SRC_IP))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"SRC_MAC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__SRC_MAC))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"SRC_PORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__SRC_PORT))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"TOB_N_LEVELS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__TOB_N_LEVELS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"TOB_N_SYMBOLS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__TOB_N_SYMBOLS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"arb_trade", &(TOP.hft_pipeline_top__DOT__arb_trade), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,161,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"clk", &(TOP.hft_pipeline_top__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"computed_index", &(TOP.hft_pipeline_top__DOT__computed_index), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"decoded_msg", &(TOP.hft_pipeline_top__DOT__decoded_msg), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,300,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"f2d_tdata", &(TOP.hft_pipeline_top__DOT__f2d_tdata), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"f2d_tkeep", &(TOP.hft_pipeline_top__DOT__f2d_tkeep), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"f2d_tlast", &(TOP.hft_pipeline_top__DOT__f2d_tlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"f2d_tready", &(TOP.hft_pipeline_top__DOT__f2d_tready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"f2d_tvalid", &(TOP.hft_pipeline_top__DOT__f2d_tvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"f2f_tdata", &(TOP.hft_pipeline_top__DOT__f2f_tdata), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"f2f_tkeep", &(TOP.hft_pipeline_top__DOT__f2f_tkeep), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"f2f_tlast", &(TOP.hft_pipeline_top__DOT__f2f_tlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"f2f_tready", &(TOP.hft_pipeline_top__DOT__f2f_tready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"f2f_tvalid", &(TOP.hft_pipeline_top__DOT__f2f_tvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"net_position", &(TOP.hft_pipeline_top__DOT__net_position), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"ol_out", &(TOP.hft_pipeline_top__DOT__ol_out), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,401,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"ol_ready", &(TOP.hft_pipeline_top__DOT__ol_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"order_count", &(TOP.hft_pipeline_top__DOT__order_count), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"pkt_sent", &(TOP.hft_pipeline_top__DOT__pkt_sent), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"rst_n", &(TOP.hft_pipeline_top__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"rx_axis_tdata", &(TOP.hft_pipeline_top__DOT__rx_axis_tdata), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"rx_axis_tkeep", &(TOP.hft_pipeline_top__DOT__rx_axis_tkeep), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"rx_axis_tlast", &(TOP.hft_pipeline_top__DOT__rx_axis_tlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"rx_axis_tready", &(TOP.hft_pipeline_top__DOT__rx_axis_tready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"rx_axis_tvalid", &(TOP.hft_pipeline_top__DOT__rx_axis_tvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"threshold", &(TOP.hft_pipeline_top__DOT__threshold), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"tob_out", &(TOP.hft_pipeline_top__DOT__tob_out), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,137,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"tob_snapshot", &(TOP.hft_pipeline_top__DOT__tob_snapshot), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,137,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"trade_signal", &(TOP.hft_pipeline_top__DOT__trade_signal), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,161,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"tx_axis_tdata", &(TOP.hft_pipeline_top__DOT__tx_axis_tdata), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"tx_axis_tkeep", &(TOP.hft_pipeline_top__DOT__tx_axis_tkeep), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"tx_axis_tlast", &(TOP.hft_pipeline_top__DOT__tx_axis_tlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"tx_axis_tready", &(TOP.hft_pipeline_top__DOT__tx_axis_tready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"tx_axis_tvalid", &(TOP.hft_pipeline_top__DOT__tx_axis_tvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"tx_enable", &(TOP.hft_pipeline_top__DOT__tx_enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"wt_wr_addr", &(TOP.hft_pipeline_top__DOT__wt_wr_addr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,8,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"wt_wr_data", &(TOP.hft_pipeline_top__DOT__wt_wr_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top.varInsert(__Vfinal,"wt_wr_en", &(TOP.hft_pipeline_top__DOT__wt_wr_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"beat_cnt_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__beat_cnt_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"beat_transferred", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__beat_transferred), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"clk", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"msg_type_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__msg_type_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"new_order_id_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__new_order_id_r), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"order_id_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__order_id_r), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"out_msg", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__out_msg), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,300,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"price_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__price_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"printable_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__printable_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"qty_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__qty_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"rst_n", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"s_axis_tdata", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__s_axis_tdata), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"s_axis_tkeep", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__s_axis_tkeep), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"s_axis_tlast", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__s_axis_tlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"s_axis_tready", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__s_axis_tready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"s_axis_tvalid", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__s_axis_tvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"side_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__side_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"state_next", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__state_next), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"state_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__state_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"symbol_index_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__symbol_index_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"symbol_seq_num_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__symbol_seq_num_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_demux.varInsert(__Vfinal,"trade_id_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__trade_id_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"BEAT_DECISION", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_filter__DOT__BEAT_DECISION))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"BEAT_ETHERTYPE", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_filter__DOT__BEAT_ETHERTYPE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"BEAT_IP_PROTO", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_filter__DOT__BEAT_IP_PROTO))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"BEAT_UDP_DPORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_filter__DOT__BEAT_UDP_DPORT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"FILTER_PORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_filter__DOT__FILTER_PORT))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"beat_count", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__beat_count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"beat_count_next", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__beat_count_next), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"beat_transferred", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__beat_transferred), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"clk", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"ethertype", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__ethertype), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"ethertype_ok", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__ethertype_ok), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"ip_proto", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__ip_proto), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"ip_proto_ok", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__ip_proto_ok), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"m_axis_tdata", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__m_axis_tdata), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"m_axis_tkeep", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__m_axis_tkeep), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"m_axis_tlast", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__m_axis_tlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"m_axis_tready", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__m_axis_tready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"m_axis_tvalid", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__m_axis_tvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"rst_n", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"s_axis_tdata", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__s_axis_tdata), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"s_axis_tkeep", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__s_axis_tkeep), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"s_axis_tlast", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__s_axis_tlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"s_axis_tready", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__s_axis_tready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"s_axis_tvalid", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__s_axis_tvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"state", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"state_next", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__state_next), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"udp_dport", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__udp_dport), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_hft_pipeline_top__u_filter.varInsert(__Vfinal,"udp_dport_ok", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__udp_dport_ok), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"CNT_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_framer__DOT__CNT_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"HEADER_BYTES", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_framer__DOT__HEADER_BYTES))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"KEEP_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_framer__DOT__KEEP_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"OFFSET", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_framer__DOT__OFFSET))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"REMAIN", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_framer__DOT__REMAIN))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"SKIP_BEATS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_framer__DOT__SKIP_BEATS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"beat_cnt_r", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__beat_cnt_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"clk", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"combined_data", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__combined_data), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"combined_keep", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__combined_keep), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"m_axis_tdata", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__m_axis_tdata), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"m_axis_tkeep", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__m_axis_tkeep), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"m_axis_tlast", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__m_axis_tlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"m_axis_tready", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__m_axis_tready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"m_axis_tvalid", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__m_axis_tvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"prev_data_r", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__prev_data_r), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"prev_keep_r", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__prev_keep_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"prev_last_r", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__prev_last_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"rst_n", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"s_axis_tdata", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__s_axis_tdata), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"s_axis_tkeep", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__s_axis_tkeep), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"s_axis_tlast", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__s_axis_tlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"s_axis_tready", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__s_axis_tready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"s_axis_tvalid", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__s_axis_tvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"state_next", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__state_next), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_hft_pipeline_top__u_framer.varInsert(__Vfinal,"state_r", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__state_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"AW", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__AW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"FRAC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__FRAC))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"IDX_SYM", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__IDX_SYM))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,8,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"N_COMPONENTS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__N_COMPONENTS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"SYMW", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__SYMW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"WW", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__WW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"abs_spread", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__abs_spread), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"actual_mid", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__actual_mid), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"actual_q", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__actual_q), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"clk", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"in_tob", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__in_tob), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,137,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"index_accum", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__index_accum), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"next_accum", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__next_accum), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"next_actual", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__next_actual), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"old_mid", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__old_mid), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,2 ,31,0 ,0,19);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"out_index", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__out_index), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"out_trade", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__out_trade), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,161,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"rst_n", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s0_delta", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_delta), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s0_is_component", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_is_component), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s0_is_index", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_is_index), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s0_new_mid", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_new_mid), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s0_sym", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_sym), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,8,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s0_two_sided", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_two_sided), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s0_valid", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s0_weight", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_weight), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s1_delta", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_delta), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s1_is_component", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_is_component), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s1_is_index", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_is_index), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s1_new_mid", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_new_mid), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s1_sym", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_sym), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,8,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s1_valid", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"s1_weight", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_weight), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"spread", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__spread), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"threshold", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__threshold), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"trade_dir", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__trade_dir), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"trade_fire", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__trade_fire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"weight_tbl", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__weight_tbl), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,2 ,31,0 ,0,19);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"weighted_delta", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__weighted_delta), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"wt_wr_addr", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__wt_wr_addr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,8,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"wt_wr_data", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__wt_wr_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb.varInsert(__Vfinal,"wt_wr_en", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__wt_wr_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_index_arb__unnamedblk1.varInsert(__Vfinal,"i", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_index_arb__unnamedblk2.varInsert(__Vfinal,"i", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__unnamedblk2__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"KEY_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__KEY_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"MAX_CHAIN", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__MAX_CHAIN))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"N_WAYS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__N_WAYS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"P_HI", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__P_HI))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"P_LO", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__P_LO))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"Q_HI", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__Q_HI))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"Q_LO", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__Q_LO))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"S_BIT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__S_BIT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"TBL_ENTRIES", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__TBL_ENTRIES))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"VALUE_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__VALUE_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"clk", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"exec_remaining", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__exec_remaining), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_del_done", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_del_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_key), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_del_not_found", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_not_found), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_del_ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_del_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_ins_done", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_ins_fail", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_fail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_ins_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_key), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_ins_ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_ins_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_ins_value", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_value), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,64,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_lu_hit", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_hit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_lu_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_key), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_lu_result_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_result_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_lu_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_lu_value", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_value), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,64,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ht_ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"lu_hit_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__lu_hit_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"lu_price_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__lu_price_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"lu_qty_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__lu_qty_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"lu_side_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__lu_side_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"msg_in", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__msg_in), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,300,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"msg_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__msg_r), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,300,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"out", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__out), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,401,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"repl_pending_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__repl_pending_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"rst_n", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"state_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__state_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"wr_key_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__wr_key_r), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup.varInsert(__Vfinal,"wr_val_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__wr_val_r), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,64,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"CHN_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__CHN_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"ENTRY_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__ENTRY_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_ROT_0", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_ROT_0))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_ROT_1", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_ROT_1))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_ROT_2", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_ROT_2))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_ROT_3", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_ROT_3))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_ROT_4", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_ROT_4))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_ROT_5", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_ROT_5))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_ROT_6", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_ROT_6))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_ROT_7", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_ROT_7))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_SEEDS_0", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_SEEDS_0))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_SEEDS_1", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_SEEDS_1))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_SEEDS_2", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_SEEDS_2))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_SEEDS_3", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_SEEDS_3))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_SEEDS_4", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_SEEDS_4))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_SEEDS_5", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_SEEDS_5))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_SEEDS_6", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_SEEDS_6))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"HASH_SEEDS_7", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_SEEDS_7))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"IDX_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__IDX_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"KEY_HI", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__KEY_HI))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"KEY_LO", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__KEY_LO))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"KEY_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__KEY_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"MAX_CHAIN", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__MAX_CHAIN))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"N_WAYS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__N_WAYS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"TBL_ENTRIES", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__TBL_ENTRIES))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"VALUE_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__VALUE_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"VAL_HI", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__VAL_HI))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"VAL_LO", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__VAL_LO))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"V_BIT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__V_BIT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"WAY_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__WAY_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"bram_addr_a", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_addr_a), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,2 ,8,0 ,0,3);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"bram_addr_b", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_addr_b), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,2 ,8,0 ,0,3);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"bram_rdata_a", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,2 ,129,0 ,0,3);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"bram_rdata_b", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,2 ,129,0 ,0,3);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"bram_wdata_b", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_wdata_b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,2 ,129,0 ,0,3);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"bram_wen_b", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_wen_b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,3);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"chain_cnt_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__chain_cnt_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"clear_addr_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__clear_addr_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,8,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"clk", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"cmp_found_empty", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__cmp_found_empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"cmp_found_existing", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__cmp_found_existing), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"cmp_sel_idx", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__cmp_sel_idx), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,8,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"cmp_sel_way", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__cmp_sel_way), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"delete_done", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"delete_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_key), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"delete_not_found", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_not_found), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"delete_ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"delete_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"evict_dst_idx_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_dst_idx_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,8,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"evict_dst_way_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_dst_way_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"evict_key_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_key_r), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"evict_slot_empty", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_slot_empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"evict_value_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_value_r), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,64,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"insert_done", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"insert_fail", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_fail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"insert_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_key), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"insert_ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"insert_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"insert_value", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_value), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,64,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"lookup_hit", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_hit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"lookup_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_key), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"lookup_result_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_result_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"lookup_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"lookup_value", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_value), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,64,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"needs_evict_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__needs_evict_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"op_is_insert_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__op_is_insert_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"op_key_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__op_key_r), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"op_value_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__op_value_r), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,64,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"rst_n", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"s1_hit", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__s1_hit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"s1_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__s1_key), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"s1_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__s1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"s1_value", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__s1_value), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,64,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"sel_idx_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__sel_idx_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,8,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"sel_way_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__sel_way_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table.varInsert(__Vfinal,"state_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__state_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__0__KET__.varInsert(__Vfinal,"mem", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__gen_bram__BRA__0__KET____DOT__mem), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,2 ,129,0 ,0,511);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__1__KET__.varInsert(__Vfinal,"mem", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__gen_bram__BRA__1__KET____DOT__mem), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,2 ,129,0 ,0,511);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__2__KET__.varInsert(__Vfinal,"mem", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__gen_bram__BRA__2__KET____DOT__mem), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,2 ,129,0 ,0,511);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__3__KET__.varInsert(__Vfinal,"mem", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__gen_bram__BRA__3__KET____DOT__mem), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,2 ,129,0 ,0,511);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk3.varInsert(__Vfinal,"w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk3__DOT__w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk4.varInsert(__Vfinal,"w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk4__DOT__w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk5.varInsert(__Vfinal,"w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk5__DOT__w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk6.varInsert(__Vfinal,"w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk6__DOT__w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk7.varInsert(__Vfinal,"w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk7__DOT__w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk8.varInsert(__Vfinal,"w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk8__DOT__w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk9.varInsert(__Vfinal,"w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk9__DOT__w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"N_LEVELS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tob__DOT__N_LEVELS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"N_SYMBOLS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tob__DOT__N_SYMBOLS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"SYM_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tob__DOT__SYM_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"add_inserted", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__add_inserted), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"add_match_found", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__add_match_found), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"add_price", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__add_price), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"add_qty", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__add_qty), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"after_add", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__after_add), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,2 ,63,0 ,0,2);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"after_rm", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__after_rm), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,2 ,63,0 ,0,2);
        //UNSUP __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"ask_book", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__ask_book), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,3 ,63,0 ,0,21 ,0,2);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"better_than", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__better_than), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        //UNSUP __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"bid_book", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__bid_book), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,3 ,63,0 ,0,21 ,0,2);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"clk", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"cur", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__cur), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,2 ,63,0 ,0,2);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"do_add", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__do_add), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"do_remove", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__do_remove), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"in_update", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__in_update), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,401,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"is_bid", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__is_bid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"msg_type", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__msg_type), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"op_side", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__op_side), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"out_tob", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__out_tob), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,137,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"rm_found", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__rm_found), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"rm_price", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__rm_price), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"rm_qty", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__rm_qty), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"rst_n", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"sym", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__sym), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_hft_pipeline_top__u_tob.varInsert(__Vfinal,"sym_valid", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__sym_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk1.varInsert(__Vfinal,"i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk10.varInsert(__Vfinal,"s", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk10__DOT__s), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk10__unnamedblk11.varInsert(__Vfinal,"l", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk10__DOT__unnamedblk11__DOT__l), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk12.varInsert(__Vfinal,"l", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk12__DOT__l), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk13.varInsert(__Vfinal,"l", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk13__DOT__l), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk2.varInsert(__Vfinal,"i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk2__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk3.varInsert(__Vfinal,"i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk3__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk3__unnamedblk4.varInsert(__Vfinal,"j", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk3__DOT__unnamedblk4__DOT__j), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk5.varInsert(__Vfinal,"i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk5__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk6.varInsert(__Vfinal,"i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk6__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk7.varInsert(__Vfinal,"i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk7__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk8.varInsert(__Vfinal,"i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk8__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tob__unnamedblk8__unnamedblk9.varInsert(__Vfinal,"j", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk8__DOT__unnamedblk9__DOT__j), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"BEAT_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__BEAT_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"COOLDOWN_CYC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__COOLDOWN_CYC))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"DST_IP", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__DST_IP))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"DST_MAC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__DST_MAC))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"DST_PORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__DST_PORT))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"IDX_SYM_ID", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__IDX_SYM_ID))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"IP_CSUM", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__IP_CSUM))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"IP_TOTAL_LEN", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__IP_TOTAL_LEN))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"LAST_BEAT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__LAST_BEAT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"MAX_POS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__MAX_POS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"N_BEATS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__N_BEATS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"ORDER_MSG_NEW", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__ORDER_MSG_NEW))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"ORDER_QTY", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__ORDER_QTY))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"PRICE_OFFSET", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__PRICE_OFFSET))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"SRC_IP", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__SRC_IP))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"SRC_MAC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__SRC_MAC))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,47,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"SRC_PORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__SRC_PORT))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"UDP_LEN", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__UDP_LEN))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"beat_data", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__beat_data), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"beat_keep", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__beat_keep), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"beat_last", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__beat_last), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"beat_r", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__beat_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"cd_cnt", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__cd_cnt), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"cd_ok", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__cd_ok), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"clk", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"enable", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"in_trade", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__in_trade), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,161,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"lat_dir", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__lat_dir), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"lat_oid", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__lat_oid), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"lat_price", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__lat_price), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"lat_spread", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__lat_spread), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"m_axis_tdata", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__m_axis_tdata), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"m_axis_tkeep", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__m_axis_tkeep), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"m_axis_tlast", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__m_axis_tlast), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"m_axis_tready", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__m_axis_tready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"m_axis_tvalid", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__m_axis_tvalid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"net_position", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__net_position), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"next_pos", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__next_pos), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"oid_seq", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__oid_seq), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"order_count", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__order_count), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"pkt_sent", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__pkt_sent), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"pos_ok", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__pos_ok), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"rst_n", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_hft_pipeline_top__u_tx.varInsert(__Vfinal,"state_r", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__state_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
    }
}
