// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(rx_axis_tkeep,7,0);
        VL_IN8(rx_axis_tvalid,0,0);
        VL_IN8(rx_axis_tlast,0,0);
        VL_OUT8(rx_axis_tready,0,0);
        VL_OUT8(tx_axis_tkeep,7,0);
        VL_OUT8(tx_axis_tvalid,0,0);
        VL_OUT8(tx_axis_tlast,0,0);
        VL_IN8(tx_axis_tready,0,0);
        VL_IN8(tx_enable,0,0);
        VL_IN8(wt_wr_en,0,0);
        VL_OUT8(ol_ready,0,0);
        VL_OUT8(pkt_sent,0,0);
        CData/*0:0*/ hft_pipeline_top__DOT__clk;
        CData/*0:0*/ hft_pipeline_top__DOT__rst_n;
        CData/*7:0*/ hft_pipeline_top__DOT__rx_axis_tkeep;
        CData/*0:0*/ hft_pipeline_top__DOT__rx_axis_tvalid;
        CData/*0:0*/ hft_pipeline_top__DOT__rx_axis_tlast;
        CData/*0:0*/ hft_pipeline_top__DOT__rx_axis_tready;
        CData/*7:0*/ hft_pipeline_top__DOT__tx_axis_tkeep;
        CData/*0:0*/ hft_pipeline_top__DOT__tx_axis_tvalid;
        CData/*0:0*/ hft_pipeline_top__DOT__tx_axis_tlast;
        CData/*0:0*/ hft_pipeline_top__DOT__tx_axis_tready;
        CData/*0:0*/ hft_pipeline_top__DOT__tx_enable;
        CData/*0:0*/ hft_pipeline_top__DOT__wt_wr_en;
        CData/*0:0*/ hft_pipeline_top__DOT__ol_ready;
        CData/*0:0*/ hft_pipeline_top__DOT__pkt_sent;
        CData/*7:0*/ hft_pipeline_top__DOT__f2f_tkeep;
        CData/*0:0*/ hft_pipeline_top__DOT__f2f_tvalid;
        CData/*0:0*/ hft_pipeline_top__DOT__f2f_tlast;
        CData/*0:0*/ hft_pipeline_top__DOT__f2f_tready;
        CData/*7:0*/ hft_pipeline_top__DOT__f2d_tkeep;
        CData/*0:0*/ hft_pipeline_top__DOT__f2d_tvalid;
        CData/*0:0*/ hft_pipeline_top__DOT__f2d_tlast;
        CData/*0:0*/ hft_pipeline_top__DOT__f2d_tready;
        CData/*0:0*/ hft_pipeline_top__DOT__u_filter__DOT__clk;
        CData/*0:0*/ hft_pipeline_top__DOT__u_filter__DOT__rst_n;
        CData/*7:0*/ hft_pipeline_top__DOT__u_filter__DOT__s_axis_tkeep;
        CData/*0:0*/ hft_pipeline_top__DOT__u_filter__DOT__s_axis_tvalid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_filter__DOT__s_axis_tlast;
        CData/*0:0*/ hft_pipeline_top__DOT__u_filter__DOT__s_axis_tready;
        CData/*7:0*/ hft_pipeline_top__DOT__u_filter__DOT__m_axis_tkeep;
        CData/*0:0*/ hft_pipeline_top__DOT__u_filter__DOT__m_axis_tvalid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_filter__DOT__m_axis_tlast;
        CData/*0:0*/ hft_pipeline_top__DOT__u_filter__DOT__m_axis_tready;
        CData/*1:0*/ hft_pipeline_top__DOT__u_filter__DOT__state;
        CData/*1:0*/ hft_pipeline_top__DOT__u_filter__DOT__state_next;
        CData/*2:0*/ hft_pipeline_top__DOT__u_filter__DOT__beat_count;
        CData/*2:0*/ hft_pipeline_top__DOT__u_filter__DOT__beat_count_next;
        CData/*7:0*/ hft_pipeline_top__DOT__u_filter__DOT__ip_proto;
        CData/*0:0*/ hft_pipeline_top__DOT__u_filter__DOT__ethertype_ok;
        CData/*0:0*/ hft_pipeline_top__DOT__u_filter__DOT__ip_proto_ok;
        CData/*0:0*/ hft_pipeline_top__DOT__u_filter__DOT__udp_dport_ok;
        CData/*0:0*/ hft_pipeline_top__DOT__u_filter__DOT__beat_transferred;
        CData/*0:0*/ hft_pipeline_top__DOT__u_framer__DOT__clk;
        CData/*0:0*/ hft_pipeline_top__DOT__u_framer__DOT__rst_n;
        CData/*7:0*/ hft_pipeline_top__DOT__u_framer__DOT__s_axis_tkeep;
        CData/*0:0*/ hft_pipeline_top__DOT__u_framer__DOT__s_axis_tvalid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_framer__DOT__s_axis_tlast;
        CData/*0:0*/ hft_pipeline_top__DOT__u_framer__DOT__s_axis_tready;
        CData/*7:0*/ hft_pipeline_top__DOT__u_framer__DOT__m_axis_tkeep;
        CData/*0:0*/ hft_pipeline_top__DOT__u_framer__DOT__m_axis_tvalid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_framer__DOT__m_axis_tlast;
    };
    struct {
        CData/*0:0*/ hft_pipeline_top__DOT__u_framer__DOT__m_axis_tready;
        CData/*1:0*/ hft_pipeline_top__DOT__u_framer__DOT__state_r;
        CData/*1:0*/ hft_pipeline_top__DOT__u_framer__DOT__state_next;
        CData/*1:0*/ hft_pipeline_top__DOT__u_framer__DOT__beat_cnt_r;
        CData/*7:0*/ hft_pipeline_top__DOT__u_framer__DOT__prev_keep_r;
        CData/*0:0*/ hft_pipeline_top__DOT__u_framer__DOT__prev_last_r;
        CData/*7:0*/ hft_pipeline_top__DOT__u_framer__DOT__combined_keep;
        CData/*0:0*/ hft_pipeline_top__DOT__u_demux__DOT__clk;
        CData/*0:0*/ hft_pipeline_top__DOT__u_demux__DOT__rst_n;
        CData/*7:0*/ hft_pipeline_top__DOT__u_demux__DOT__s_axis_tkeep;
        CData/*0:0*/ hft_pipeline_top__DOT__u_demux__DOT__s_axis_tvalid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_demux__DOT__s_axis_tlast;
        CData/*0:0*/ hft_pipeline_top__DOT__u_demux__DOT__s_axis_tready;
        CData/*1:0*/ hft_pipeline_top__DOT__u_demux__DOT__state_r;
        CData/*1:0*/ hft_pipeline_top__DOT__u_demux__DOT__state_next;
        CData/*2:0*/ hft_pipeline_top__DOT__u_demux__DOT__beat_cnt_r;
        CData/*0:0*/ hft_pipeline_top__DOT__u_demux__DOT__beat_transferred;
        CData/*2:0*/ hft_pipeline_top__DOT__u_demux__DOT__msg_type_r;
        CData/*0:0*/ hft_pipeline_top__DOT__u_demux__DOT__side_r;
        CData/*7:0*/ hft_pipeline_top__DOT__u_demux__DOT__printable_r;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__clk;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__rst_n;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ready;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ready;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_valid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_result_valid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_hit;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_valid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_ready;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_done;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_fail;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_valid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_ready;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_done;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_not_found;
        CData/*3:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__state_r;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__lu_hit_r;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__lu_side_r;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__repl_pending_r;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__clk;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__rst_n;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__ready;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_valid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_result_valid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_hit;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_valid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_ready;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_done;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_fail;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_valid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_ready;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_done;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_not_found;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__s1_valid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__s1_hit;
        CData/*3:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__state_r;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__op_is_insert_r;
        CData/*1:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__sel_way_r;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__needs_evict_r;
        CData/*1:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_dst_way_r;
        CData/*4:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__chain_cnt_r;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__cmp_found_existing;
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__cmp_found_empty;
        CData/*1:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__cmp_sel_way;
    };
    struct {
        CData/*0:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_slot_empty;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_h3945d898__0;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tob__DOT__clk;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tob__DOT__rst_n;
        CData/*4:0*/ hft_pipeline_top__DOT__u_tob__DOT__sym;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tob__DOT__sym_valid;
        CData/*2:0*/ hft_pipeline_top__DOT__u_tob__DOT__msg_type;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tob__DOT__do_remove;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tob__DOT__do_add;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tob__DOT__op_side;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tob__DOT__is_bid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tob__DOT__rm_found;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tob__DOT__add_match_found;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tob__DOT__add_inserted;
        CData/*2:0*/ hft_pipeline_top__DOT__u_tob__DOT__better_than;
        CData/*0:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__clk;
        CData/*0:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__rst_n;
        CData/*0:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__wt_wr_en;
        CData/*0:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s0_valid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s0_is_index;
        CData/*0:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s0_is_component;
        CData/*0:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s0_two_sided;
        CData/*0:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s1_valid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s1_is_index;
        CData/*0:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s1_is_component;
        CData/*0:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__trade_fire;
        CData/*0:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__trade_dir;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tx__DOT__clk;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tx__DOT__rst_n;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tx__DOT__enable;
        CData/*7:0*/ hft_pipeline_top__DOT__u_tx__DOT__m_axis_tkeep;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tx__DOT__m_axis_tvalid;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tx__DOT__m_axis_tlast;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tx__DOT__m_axis_tready;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tx__DOT__pkt_sent;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tx__DOT__state_r;
        CData/*3:0*/ hft_pipeline_top__DOT__u_tx__DOT__beat_r;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tx__DOT__lat_dir;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tx__DOT__cd_ok;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tx__DOT__pos_ok;
        CData/*7:0*/ hft_pipeline_top__DOT__u_tx__DOT__beat_keep;
        CData/*0:0*/ hft_pipeline_top__DOT__u_tx__DOT__beat_last;
        CData/*0:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__5____Vlvbound_h61001783__0;
        CData/*0:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__7____Vlvbound_h61001783__0;
        CData/*0:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__8____Vlvbound_h61001783__0;
        CData/*0:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__9____Vlvbound_h61001783__0;
        CData/*0:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__10____Vlvbound_h61001783__0;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__14__b0;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__14__b1;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__15__b0;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__15__b1;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__15__b2;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__15__b3;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__15__b4;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__15__b5;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__15__b6;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__15__b7;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__16__b2;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__16__b3;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__16__b4;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__16__b5;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__16__b6;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__16__b7;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__17__b2;
    };
    struct {
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__17__b3;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__17__b4;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__17__b5;
        CData/*7:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__18__b4;
        CData/*0:0*/ __VdlySet__hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_b__v0;
        CData/*0:0*/ __VdlySet__hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_b__v1;
        CData/*0:0*/ __VdlySet__hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_b__v2;
        CData/*0:0*/ __VdlySet__hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_b__v3;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__hft_pipeline_top__DOT__u_filter__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__hft_pipeline_top__DOT__u_framer__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__hft_pipeline_top__DOT__u_demux__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__hft_pipeline_top__DOT__u_order_lookup__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__hft_pipeline_top__DOT__u_order_lookup__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__hft_pipeline_top__DOT__u_tob__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__hft_pipeline_top__DOT__u_index_arb__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__hft_pipeline_top__DOT__u_tx__DOT__clk__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        VL_IN16(wt_wr_addr,8,0);
        SData/*8:0*/ hft_pipeline_top__DOT__wt_wr_addr;
        SData/*15:0*/ hft_pipeline_top__DOT__u_filter__DOT__ethertype;
        SData/*15:0*/ hft_pipeline_top__DOT__u_filter__DOT__udp_dport;
        SData/*8:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__clear_addr_r;
        SData/*8:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__sel_idx_r;
        SData/*8:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_dst_idx_r;
        SData/*8:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__cmp_sel_idx;
        SData/*8:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__wt_wr_addr;
        SData/*8:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s0_sym;
        SData/*8:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s1_sym;
        SData/*8:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__5__Vfuncout;
        SData/*8:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__5__folded;
        SData/*8:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__7__Vfuncout;
        SData/*8:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__7__folded;
        SData/*8:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__8__Vfuncout;
        SData/*8:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__8__folded;
        SData/*8:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__9__Vfuncout;
        SData/*8:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__9__folded;
        SData/*8:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__10__Vfuncout;
        SData/*8:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__10__folded;
        VL_IN(wt_wr_data,31,0);
        VL_OUT(order_count,31,0);
        VL_OUT(net_position,31,0);
        IData/*31:0*/ hft_pipeline_top__DOT__wt_wr_data;
        IData/*31:0*/ hft_pipeline_top__DOT__order_count;
        IData/*31:0*/ hft_pipeline_top__DOT__net_position;
        IData/*31:0*/ hft_pipeline_top__DOT__u_demux__DOT__symbol_index_r;
        IData/*31:0*/ hft_pipeline_top__DOT__u_demux__DOT__symbol_seq_num_r;
        IData/*31:0*/ hft_pipeline_top__DOT__u_demux__DOT__price_r;
        IData/*31:0*/ hft_pipeline_top__DOT__u_demux__DOT__qty_r;
        IData/*31:0*/ hft_pipeline_top__DOT__u_demux__DOT__trade_id_r;
        VlWide<3>/*64:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_value;
        VlWide<3>/*64:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_value;
        IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__exec_remaining;
        IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__lu_price_r;
        IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__lu_qty_r;
        VlWide<3>/*64:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__wr_val_r;
        VlWide<3>/*64:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_value;
        VlWide<3>/*64:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_value;
    };
    struct {
        VlWide<3>/*64:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__s1_value;
        VlWide<3>/*64:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__op_value_r;
        VlWide<3>/*64:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_value_r;
        IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk3__DOT__w;
        IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk4__DOT__w;
        IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk5__DOT__w;
        IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk6__DOT__w;
        IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk7__DOT__w;
        IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk8__DOT__w;
        IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk9__DOT__w;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_hf307708e__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_hf30588e6__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_haf3ac47c__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_haf3acc64__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_h813121f6__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_h81311a8e__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_h104c0e2d__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_h104c1625__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_hc27b3eda__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_hc27b46c2__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__rm_price;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__rm_qty;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__add_price;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__add_qty;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk3__DOT__unnamedblk4__DOT__j;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk8__DOT__unnamedblk9__DOT__j;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk12__DOT__l;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk13__DOT__l;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk10__DOT__s;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__unnamedblk10__DOT__unnamedblk11__DOT__l;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT____Vlvbound_h0e01100d__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT____Vlvbound_hc531679c__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT____Vlvbound_hd9b7c195__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT____Vlvbound_hd419c78d__0;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__wt_wr_data;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__actual_mid;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s0_new_mid;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s0_weight;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s1_new_mid;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s1_weight;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__next_actual;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__order_count;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__net_position;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__lat_price;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__cd_cnt;
        IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__next_pos;
        IData/*31:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__5__way;
        IData/*31:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__5__rot;
        IData/*31:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__7__way;
        IData/*31:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__7__rot;
        IData/*31:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__8__way;
        IData/*31:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__8__rot;
        IData/*31:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__9__way;
        IData/*31:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__9__rot;
        IData/*31:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__10__way;
    };
    struct {
        IData/*31:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__10__rot;
        VlWide<5>/*129:0*/ __VdlyVal__hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_b__v0;
        VlWide<5>/*129:0*/ __VdlyVal__hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_b__v1;
        VlWide<5>/*129:0*/ __VdlyVal__hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_b__v2;
        VlWide<5>/*129:0*/ __VdlyVal__hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_b__v3;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(rx_axis_tdata,63,0);
        VL_OUT64(tx_axis_tdata,63,0);
        VL_IN64(threshold,63,0);
        VL_OUTW(tob_snapshot,137,0,5);
        VL_OUTW(trade_signal,161,0,6);
        VL_OUT64(computed_index,63,0);
        QData/*63:0*/ hft_pipeline_top__DOT__rx_axis_tdata;
        QData/*63:0*/ hft_pipeline_top__DOT__tx_axis_tdata;
        QData/*63:0*/ hft_pipeline_top__DOT__threshold;
        VlWide<5>/*137:0*/ hft_pipeline_top__DOT__tob_snapshot;
        VlWide<6>/*161:0*/ hft_pipeline_top__DOT__trade_signal;
        QData/*63:0*/ hft_pipeline_top__DOT__computed_index;
        QData/*63:0*/ hft_pipeline_top__DOT__f2f_tdata;
        QData/*63:0*/ hft_pipeline_top__DOT__f2d_tdata;
        VlWide<10>/*300:0*/ hft_pipeline_top__DOT__decoded_msg;
        VlWide<13>/*401:0*/ hft_pipeline_top__DOT__ol_out;
        VlWide<5>/*137:0*/ hft_pipeline_top__DOT__tob_out;
        VlWide<6>/*161:0*/ hft_pipeline_top__DOT__arb_trade;
        QData/*63:0*/ hft_pipeline_top__DOT__u_filter__DOT__s_axis_tdata;
        QData/*63:0*/ hft_pipeline_top__DOT__u_filter__DOT__m_axis_tdata;
        QData/*63:0*/ hft_pipeline_top__DOT__u_framer__DOT__s_axis_tdata;
        QData/*63:0*/ hft_pipeline_top__DOT__u_framer__DOT__m_axis_tdata;
        QData/*63:0*/ hft_pipeline_top__DOT__u_framer__DOT__prev_data_r;
        QData/*63:0*/ hft_pipeline_top__DOT__u_framer__DOT__combined_data;
        QData/*63:0*/ hft_pipeline_top__DOT__u_demux__DOT__s_axis_tdata;
        VlWide<10>/*300:0*/ hft_pipeline_top__DOT__u_demux__DOT__out_msg;
        QData/*63:0*/ hft_pipeline_top__DOT__u_demux__DOT__order_id_r;
        QData/*63:0*/ hft_pipeline_top__DOT__u_demux__DOT__new_order_id_r;
        VlWide<10>/*300:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__msg_in;
        VlWide<13>/*401:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__out;
        QData/*63:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_key;
        QData/*63:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_key;
        QData/*63:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_key;
        VlWide<10>/*300:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__msg_r;
        QData/*63:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__wr_key_r;
        QData/*63:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_key;
        QData/*63:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_key;
        QData/*63:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_key;
        QData/*63:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__s1_key;
        QData/*63:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__op_key_r;
        QData/*63:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_key_r;
        QData/*63:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_h0f0b0d31__0;
        QData/*63:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_h247cbf38__0;
        QData/*63:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_hd5cb8263__0;
        QData/*63:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_hd59551cd__0;
        QData/*63:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_h332dfccf__0;
        QData/*63:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_hd32e541e__0;
        QData/*63:0*/ hft_pipeline_top__DOT__u_tob__DOT____Vlvbound_h99a7bc22__0;
        VlWide<13>/*401:0*/ hft_pipeline_top__DOT__u_tob__DOT__in_update;
        VlWide<5>/*137:0*/ hft_pipeline_top__DOT__u_tob__DOT__out_tob;
        VlWide<5>/*137:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__in_tob;
        QData/*63:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__threshold;
        VlWide<6>/*161:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__out_trade;
        QData/*63:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__out_index;
        QData/*63:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__index_accum;
        QData/*32:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s0_delta;
        QData/*32:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__s1_delta;
        QData/*63:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__weighted_delta;
    };
    struct {
        QData/*63:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__next_accum;
        QData/*63:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__actual_q;
        QData/*63:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__spread;
        QData/*63:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__abs_spread;
        VlWide<6>/*161:0*/ hft_pipeline_top__DOT__u_tx__DOT__in_trade;
        QData/*63:0*/ hft_pipeline_top__DOT__u_tx__DOT__m_axis_tdata;
        QData/*63:0*/ hft_pipeline_top__DOT__u_tx__DOT__lat_spread;
        QData/*63:0*/ hft_pipeline_top__DOT__u_tx__DOT__lat_oid;
        QData/*63:0*/ hft_pipeline_top__DOT__u_tx__DOT__oid_seq;
        QData/*63:0*/ hft_pipeline_top__DOT__u_tx__DOT__beat_data;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__5__key;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__5__seed_k;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__5__mixed;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__7__key;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__7__seed_k;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__7__mixed;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__8__key;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__8__seed_k;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__8__mixed;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__9__key;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__9__seed_k;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__9__mixed;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__10__key;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__10__seed_k;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__hash_fn__10__mixed;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__14__Vfuncout;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__15__Vfuncout;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__16__Vfuncout;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__17__Vfuncout;
        QData/*63:0*/ __Vfunc_hft_pipeline_top__DOT__u_tx__DOT__pk__18__Vfuncout;
        VlUnpacked<SData/*8:0*/, 4> hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_addr_a;
        VlUnpacked<VlWide<5>/*129:0*/, 4> hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_a;
        VlUnpacked<SData/*8:0*/, 4> hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_addr_b;
        VlUnpacked<VlWide<5>/*129:0*/, 4> hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_b;
        VlUnpacked<VlWide<5>/*129:0*/, 4> hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_wdata_b;
        VlUnpacked<CData/*0:0*/, 4> hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_wen_b;
        VlUnpacked<VlWide<5>/*129:0*/, 512> hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__gen_bram__BRA__0__KET____DOT__mem;
        VlUnpacked<VlWide<5>/*129:0*/, 512> hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__gen_bram__BRA__1__KET____DOT__mem;
        VlUnpacked<VlWide<5>/*129:0*/, 512> hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__gen_bram__BRA__2__KET____DOT__mem;
        VlUnpacked<VlWide<5>/*129:0*/, 512> hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__gen_bram__BRA__3__KET____DOT__mem;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 3>, 22> hft_pipeline_top__DOT__u_tob__DOT__bid_book;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 3>, 22> hft_pipeline_top__DOT__u_tob__DOT__ask_book;
        VlUnpacked<QData/*63:0*/, 3> hft_pipeline_top__DOT__u_tob__DOT__cur;
        VlUnpacked<QData/*63:0*/, 3> hft_pipeline_top__DOT__u_tob__DOT__after_rm;
        VlUnpacked<QData/*63:0*/, 3> hft_pipeline_top__DOT__u_tob__DOT__after_add;
        VlUnpacked<IData/*31:0*/, 20> hft_pipeline_top__DOT__u_index_arb__DOT__weight_tbl;
        VlUnpacked<IData/*31:0*/, 20> hft_pipeline_top__DOT__u_index_arb__DOT__old_mid;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<VlUnpacked<QData/*63:0*/, 3>, 22>, true, QData/*63:0*/, 2> __VdlyCommitQueuehft_pipeline_top__DOT__u_tob__DOT__bid_book;
    VlNBACommitQueue<VlUnpacked<VlUnpacked<QData/*63:0*/, 3>, 22>, true, QData/*63:0*/, 2> __VdlyCommitQueuehft_pipeline_top__DOT__u_tob__DOT__ask_book;
    VlNBACommitQueue<VlUnpacked<IData/*31:0*/, 20>, false, IData/*31:0*/, 1> __VdlyCommitQueuehft_pipeline_top__DOT__u_index_arb__DOT__weight_tbl;
    VlNBACommitQueue<VlUnpacked<IData/*31:0*/, 20>, false, IData/*31:0*/, 1> __VdlyCommitQueuehft_pipeline_top__DOT__u_index_arb__DOT__old_mid;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr CData/*2:0*/ hft_pipeline_top__DOT__u_filter__DOT__BEAT_ETHERTYPE = 1U;
    static constexpr CData/*2:0*/ hft_pipeline_top__DOT__u_filter__DOT__BEAT_IP_PROTO = 2U;
    static constexpr CData/*2:0*/ hft_pipeline_top__DOT__u_filter__DOT__BEAT_UDP_DPORT = 4U;
    static constexpr CData/*2:0*/ hft_pipeline_top__DOT__u_filter__DOT__BEAT_DECISION = 5U;
    static constexpr SData/*15:0*/ hft_pipeline_top__DOT__FILTER_PORT = 0x2b5dU;
    static constexpr SData/*8:0*/ hft_pipeline_top__DOT__IDX_SYM = 0x0014U;
    static constexpr SData/*15:0*/ hft_pipeline_top__DOT__SRC_PORT = 0x3039U;
    static constexpr SData/*15:0*/ hft_pipeline_top__DOT__DST_PORT = 0xd431U;
    static constexpr SData/*15:0*/ hft_pipeline_top__DOT__u_filter__DOT__FILTER_PORT = 0x2b5dU;
    static constexpr SData/*8:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__IDX_SYM = 0x0014U;
    static constexpr SData/*15:0*/ hft_pipeline_top__DOT__u_tx__DOT__SRC_PORT = 0x3039U;
    static constexpr SData/*15:0*/ hft_pipeline_top__DOT__u_tx__DOT__DST_PORT = 0xd431U;
    static constexpr SData/*15:0*/ hft_pipeline_top__DOT__u_tx__DOT__ORDER_MSG_NEW = 1U;
    static constexpr SData/*15:0*/ hft_pipeline_top__DOT__u_tx__DOT__IP_TOTAL_LEN = 0x003cU;
    static constexpr SData/*15:0*/ hft_pipeline_top__DOT__u_tx__DOT__UDP_LEN = 0x0028U;
    static constexpr SData/*15:0*/ hft_pipeline_top__DOT__u_tx__DOT__IP_CSUM = 0x26afU;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__HEADER_BYTES = 0x0000000aU;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__HT_N_WAYS = 4U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__HT_TBL_ENTRIES = 0x00000200U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__HT_MAX_CHAIN = 0x00000010U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__TOB_N_LEVELS = 3U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__TOB_N_SYMBOLS = 0x00000016U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__N_COMPONENTS = 0x00000014U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__SRC_IP = 0x0a000001U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__DST_IP = 0x0a000002U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__ORDER_QTY = 0x00000064U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__COOLDOWN_CYC = 0x00000014U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__MAX_POS = 0x00002710U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__PRICE_OFFSET = 0x0000000aU;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__IDX_SYM_ID = 0x00000014U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_framer__DOT__HEADER_BYTES = 0x0000000aU;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_framer__DOT__KEEP_W = 8U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_framer__DOT__SKIP_BEATS = 1U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_framer__DOT__OFFSET = 2U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_framer__DOT__REMAIN = 6U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_framer__DOT__CNT_W = 2U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__N_WAYS = 4U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__TBL_ENTRIES = 0x00000200U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__MAX_CHAIN = 0x00000010U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__KEY_W = 0x00000040U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__VALUE_W = 0x00000041U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__P_HI = 0x00000040U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__P_LO = 0x00000021U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__Q_HI = 0x00000020U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__Q_LO = 1U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__S_BIT = 0U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__KEY_W = 0x00000040U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__VALUE_W = 0x00000041U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__N_WAYS = 4U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__TBL_ENTRIES = 0x00000200U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__MAX_CHAIN = 0x00000010U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__IDX_W = 9U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__ENTRY_W = 0x00000082U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__WAY_W = 2U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__CHN_W = 5U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__V_BIT = 0x00000081U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__KEY_HI = 0x00000080U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__KEY_LO = 0x00000041U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__VAL_HI = 0x00000040U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__VAL_LO = 0U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__N_LEVELS = 3U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__N_SYMBOLS = 0x00000016U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tob__DOT__SYM_W = 5U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__N_COMPONENTS = 0x00000014U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__FRAC = 0x00000014U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__AW = 0x00000040U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__WW = 0x00000020U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_index_arb__DOT__SYMW = 9U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__SRC_IP = 0x0a000001U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__DST_IP = 0x0a000002U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__ORDER_QTY = 0x00000064U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__COOLDOWN_CYC = 0x00000014U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__MAX_POS = 0x00002710U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__PRICE_OFFSET = 0x0000000aU;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__IDX_SYM_ID = 0x00000014U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__N_BEATS = 0x0000000aU;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__LAST_BEAT = 9U;
    static constexpr IData/*31:0*/ hft_pipeline_top__DOT__u_tx__DOT__BEAT_W = 4U;
    static constexpr QData/*47:0*/ hft_pipeline_top__DOT__SRC_MAC = 0x0000deadbeefcafeULL;
    static constexpr QData/*47:0*/ hft_pipeline_top__DOT__DST_MAC = 0x000001005e000001ULL;
    static constexpr QData/*47:0*/ hft_pipeline_top__DOT__u_tx__DOT__SRC_MAC = 0x0000deadbeefcafeULL;
    static constexpr QData/*47:0*/ hft_pipeline_top__DOT__u_tx__DOT__DST_MAC = 0x000001005e000001ULL;
    static constexpr VlUnpacked<QData/*63:0*/, 8> hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_SEEDS = {{
        0x9e3779b97f4a7c15ULL, 0x517cc1b727220a95ULL,
        0x6c62272e07bb0142ULL, 0xbf58476d1ce4e5b9ULL,
        0x94d049bb133111ebULL, 0xc6a4a7935bd1e995ULL,
        0xe7037ed1a0b428dbULL, 0x27d4eb2f165b7d1aULL
    }};
    static constexpr VlUnpacked<IData/*31:0*/, 8> hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_ROT = {{
        3U, 7U, 0x0000000dU, 0x00000013U,
        0x00000017U, 0x0000001dU, 0x00000025U, 0x00000029U
    }};

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
