// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup top module instance
    , TOP{this, namep}
{
    // Check resources
    Verilated::stackCheck(1334);
    // Setup sub module instances
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-10);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscopep_TOP = new VerilatedScope{this, "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top = new VerilatedScope{this, "hft_pipeline_top", "hft_pipeline_top", "hft_pipeline_top", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_hft_pipeline_top__u_demux = new VerilatedScope{this, "hft_pipeline_top.u_demux", "u_demux", "xdp_msg_demux", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_hft_pipeline_top__u_filter = new VerilatedScope{this, "hft_pipeline_top.u_filter", "u_filter", "ipv4_udp_port_filter", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_hft_pipeline_top__u_framer = new VerilatedScope{this, "hft_pipeline_top.u_framer", "u_framer", "xdp_packet_framer", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_hft_pipeline_top__u_index_arb = new VerilatedScope{this, "hft_pipeline_top.u_index_arb", "u_index_arb", "index_arb_engine", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_hft_pipeline_top__u_index_arb__unnamedblk1 = new VerilatedScope{this, "hft_pipeline_top.u_index_arb.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_index_arb__unnamedblk2 = new VerilatedScope{this, "hft_pipeline_top.u_index_arb.unnamedblk2", "unnamedblk2", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_order_lookup = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup", "u_order_lookup", "order_lookup", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup.u_order_table", "u_order_table", "skewed_hash_table", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__0__KET__ = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup.u_order_table.gen_bram[0]", "gen_bram[0]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__1__KET__ = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup.u_order_table.gen_bram[1]", "gen_bram[1]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__2__KET__ = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup.u_order_table.gen_bram[2]", "gen_bram[2]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__3__KET__ = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup.u_order_table.gen_bram[3]", "gen_bram[3]", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk3 = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk3", "unnamedblk3", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk4 = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk4", "unnamedblk4", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk5 = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk5", "unnamedblk5", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk6 = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk6", "unnamedblk6", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk7 = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk7", "unnamedblk7", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk8 = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk8", "unnamedblk8", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk9 = new VerilatedScope{this, "hft_pipeline_top.u_order_lookup.u_order_table.unnamedblk9", "unnamedblk9", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob = new VerilatedScope{this, "hft_pipeline_top.u_tob", "u_tob", "top_of_book", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk1 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk10 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk10", "unnamedblk10", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk10__unnamedblk11 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk10.unnamedblk11", "unnamedblk11", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk12 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk12", "unnamedblk12", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk13 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk13", "unnamedblk13", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk2 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk2", "unnamedblk2", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk3 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk3", "unnamedblk3", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk3__unnamedblk4 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk3.unnamedblk4", "unnamedblk4", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk5 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk5", "unnamedblk5", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk6 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk6", "unnamedblk6", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk7 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk7", "unnamedblk7", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk8 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk8", "unnamedblk8", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk8__unnamedblk9 = new VerilatedScope{this, "hft_pipeline_top.u_tob.unnamedblk8.unnamedblk9", "unnamedblk9", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_hft_pipeline_top__u_tx = new VerilatedScope{this, "hft_pipeline_top.u_tx", "u_tx", "order_gen_tx", -9, VerilatedScope::SCOPE_MODULE};
    // Set up scope hierarchy
    __Vhier.add(0, __Vscopep_hft_pipeline_top);
    __Vhier.add(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_demux);
    __Vhier.add(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_filter);
    __Vhier.add(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_framer);
    __Vhier.add(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_index_arb);
    __Vhier.add(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_order_lookup);
    __Vhier.add(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_tob);
    __Vhier.add(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_tx);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_index_arb, __Vscopep_hft_pipeline_top__u_index_arb__unnamedblk1);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_index_arb, __Vscopep_hft_pipeline_top__u_index_arb__unnamedblk2);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_order_lookup, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__0__KET__);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__1__KET__);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__2__KET__);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__3__KET__);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk3);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk4);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk5);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk6);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk7);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk8);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk9);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk1);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk10);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk12);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk13);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk2);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk3);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk5);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk6);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk7);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk8);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob__unnamedblk10, __Vscopep_hft_pipeline_top__u_tob__unnamedblk10__unnamedblk11);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob__unnamedblk3, __Vscopep_hft_pipeline_top__u_tob__unnamedblk3__unnamedblk4);
    __Vhier.add(__Vscopep_hft_pipeline_top__u_tob__unnamedblk8, __Vscopep_hft_pipeline_top__u_tob__unnamedblk8__unnamedblk9);
    // Setup export functions - final: 0
    // Setup export functions - final: 1
    // Setup public variables
    __Vscopep_TOP->varInsert("clk", &(TOP.clk), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("computed_index", &(TOP.computed_index), false, VLVT_UINT64, VLVD_OUT|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_TOP->varInsert("net_position", &(TOP.net_position), false, VLVT_UINT32, VLVD_OUT|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("ol_ready", &(TOP.ol_ready), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("order_count", &(TOP.order_count), false, VLVT_UINT32, VLVD_OUT|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("pkt_sent", &(TOP.pkt_sent), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("rst_n", &(TOP.rst_n), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("rx_axis_tdata", &(TOP.rx_axis_tdata), false, VLVT_UINT64, VLVD_IN|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_TOP->varInsert("rx_axis_tkeep", &(TOP.rx_axis_tkeep), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_TOP->varInsert("rx_axis_tlast", &(TOP.rx_axis_tlast), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("rx_axis_tready", &(TOP.rx_axis_tready), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("rx_axis_tvalid", &(TOP.rx_axis_tvalid), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("threshold", &(TOP.threshold), false, VLVT_UINT64, VLVD_IN|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_TOP->varInsert("tob_snapshot", &(TOP.tob_snapshot), false, VLVT_WDATA, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,137,0);
    __Vscopep_TOP->varInsert("trade_signal", &(TOP.trade_signal), false, VLVT_WDATA, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,161,0);
    __Vscopep_TOP->varInsert("tx_axis_tdata", &(TOP.tx_axis_tdata), false, VLVT_UINT64, VLVD_OUT|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_TOP->varInsert("tx_axis_tkeep", &(TOP.tx_axis_tkeep), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_TOP->varInsert("tx_axis_tlast", &(TOP.tx_axis_tlast), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("tx_axis_tready", &(TOP.tx_axis_tready), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("tx_axis_tvalid", &(TOP.tx_axis_tvalid), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("tx_enable", &(TOP.tx_enable), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("wt_wr_addr", &(TOP.wt_wr_addr), false, VLVT_UINT16, VLVD_IN|VLVF_PUB_RW, 0, 1 ,8,0);
    __Vscopep_TOP->varInsert("wt_wr_data", &(TOP.wt_wr_data), false, VLVT_UINT32, VLVD_IN|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("wt_wr_en", &(TOP.wt_wr_en), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("COOLDOWN_CYC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__COOLDOWN_CYC))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("DST_IP", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__DST_IP))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("DST_MAC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__DST_MAC))), true, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,47,0);
    __Vscopep_hft_pipeline_top->varInsert("DST_PORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__DST_PORT))), true, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_hft_pipeline_top->varInsert("FILTER_PORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__FILTER_PORT))), true, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_hft_pipeline_top->varInsert("HEADER_BYTES", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__HEADER_BYTES))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("HT_MAX_CHAIN", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__HT_MAX_CHAIN))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("HT_N_WAYS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__HT_N_WAYS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("HT_TBL_ENTRIES", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__HT_TBL_ENTRIES))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("IDX_SYM", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__IDX_SYM))), true, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,8,0);
    __Vscopep_hft_pipeline_top->varInsert("IDX_SYM_ID", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__IDX_SYM_ID))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("MAX_POS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__MAX_POS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("N_COMPONENTS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__N_COMPONENTS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("ORDER_QTY", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__ORDER_QTY))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("PRICE_OFFSET", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__PRICE_OFFSET))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("SRC_IP", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__SRC_IP))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("SRC_MAC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__SRC_MAC))), true, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,47,0);
    __Vscopep_hft_pipeline_top->varInsert("SRC_PORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__SRC_PORT))), true, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_hft_pipeline_top->varInsert("TOB_N_LEVELS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__TOB_N_LEVELS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("TOB_N_SYMBOLS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__TOB_N_SYMBOLS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("arb_trade", &(TOP.hft_pipeline_top__DOT__arb_trade), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,161,0);
    __Vscopep_hft_pipeline_top->varInsert("clk", &(TOP.hft_pipeline_top__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("computed_index", &(TOP.hft_pipeline_top__DOT__computed_index), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top->varInsert("decoded_msg", &(TOP.hft_pipeline_top__DOT__decoded_msg), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,300,0);
    __Vscopep_hft_pipeline_top->varInsert("f2d_tdata", &(TOP.hft_pipeline_top__DOT__f2d_tdata), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top->varInsert("f2d_tkeep", &(TOP.hft_pipeline_top__DOT__f2d_tkeep), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top->varInsert("f2d_tlast", &(TOP.hft_pipeline_top__DOT__f2d_tlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("f2d_tready", &(TOP.hft_pipeline_top__DOT__f2d_tready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("f2d_tvalid", &(TOP.hft_pipeline_top__DOT__f2d_tvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("f2f_tdata", &(TOP.hft_pipeline_top__DOT__f2f_tdata), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top->varInsert("f2f_tkeep", &(TOP.hft_pipeline_top__DOT__f2f_tkeep), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top->varInsert("f2f_tlast", &(TOP.hft_pipeline_top__DOT__f2f_tlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("f2f_tready", &(TOP.hft_pipeline_top__DOT__f2f_tready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("f2f_tvalid", &(TOP.hft_pipeline_top__DOT__f2f_tvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("net_position", &(TOP.hft_pipeline_top__DOT__net_position), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("ol_out", &(TOP.hft_pipeline_top__DOT__ol_out), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,401,0);
    __Vscopep_hft_pipeline_top->varInsert("ol_ready", &(TOP.hft_pipeline_top__DOT__ol_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("order_count", &(TOP.hft_pipeline_top__DOT__order_count), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("pkt_sent", &(TOP.hft_pipeline_top__DOT__pkt_sent), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("rst_n", &(TOP.hft_pipeline_top__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("rx_axis_tdata", &(TOP.hft_pipeline_top__DOT__rx_axis_tdata), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top->varInsert("rx_axis_tkeep", &(TOP.hft_pipeline_top__DOT__rx_axis_tkeep), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top->varInsert("rx_axis_tlast", &(TOP.hft_pipeline_top__DOT__rx_axis_tlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("rx_axis_tready", &(TOP.hft_pipeline_top__DOT__rx_axis_tready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("rx_axis_tvalid", &(TOP.hft_pipeline_top__DOT__rx_axis_tvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("threshold", &(TOP.hft_pipeline_top__DOT__threshold), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top->varInsert("tob_out", &(TOP.hft_pipeline_top__DOT__tob_out), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,137,0);
    __Vscopep_hft_pipeline_top->varInsert("tob_snapshot", &(TOP.hft_pipeline_top__DOT__tob_snapshot), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,137,0);
    __Vscopep_hft_pipeline_top->varInsert("trade_signal", &(TOP.hft_pipeline_top__DOT__trade_signal), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,161,0);
    __Vscopep_hft_pipeline_top->varInsert("tx_axis_tdata", &(TOP.hft_pipeline_top__DOT__tx_axis_tdata), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top->varInsert("tx_axis_tkeep", &(TOP.hft_pipeline_top__DOT__tx_axis_tkeep), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top->varInsert("tx_axis_tlast", &(TOP.hft_pipeline_top__DOT__tx_axis_tlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("tx_axis_tready", &(TOP.hft_pipeline_top__DOT__tx_axis_tready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("tx_axis_tvalid", &(TOP.hft_pipeline_top__DOT__tx_axis_tvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("tx_enable", &(TOP.hft_pipeline_top__DOT__tx_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top->varInsert("wt_wr_addr", &(TOP.hft_pipeline_top__DOT__wt_wr_addr), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,8,0);
    __Vscopep_hft_pipeline_top->varInsert("wt_wr_data", &(TOP.hft_pipeline_top__DOT__wt_wr_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top->varInsert("wt_wr_en", &(TOP.hft_pipeline_top__DOT__wt_wr_en), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("beat_cnt_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__beat_cnt_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("beat_transferred", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__beat_transferred), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("clk", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("msg_type_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__msg_type_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("new_order_id_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__new_order_id_r), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("order_id_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__order_id_r), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("out_msg", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__out_msg), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,300,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("price_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__price_r), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("printable_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__printable_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("qty_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__qty_r), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("rst_n", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("s_axis_tdata", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__s_axis_tdata), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("s_axis_tkeep", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__s_axis_tkeep), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("s_axis_tlast", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__s_axis_tlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("s_axis_tready", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__s_axis_tready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("s_axis_tvalid", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__s_axis_tvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("side_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__side_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("state_next", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__state_next), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("state_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__state_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("symbol_index_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__symbol_index_r), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("symbol_seq_num_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__symbol_seq_num_r), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_demux->varInsert("trade_id_r", &(TOP.hft_pipeline_top__DOT__u_demux__DOT__trade_id_r), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("BEAT_DECISION", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_filter__DOT__BEAT_DECISION))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("BEAT_ETHERTYPE", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_filter__DOT__BEAT_ETHERTYPE))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("BEAT_IP_PROTO", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_filter__DOT__BEAT_IP_PROTO))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("BEAT_UDP_DPORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_filter__DOT__BEAT_UDP_DPORT))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("FILTER_PORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_filter__DOT__FILTER_PORT))), true, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("beat_count", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__beat_count), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("beat_count_next", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__beat_count_next), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("beat_transferred", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__beat_transferred), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("clk", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("ethertype", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__ethertype), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("ethertype_ok", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__ethertype_ok), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("ip_proto", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__ip_proto), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("ip_proto_ok", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__ip_proto_ok), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("m_axis_tdata", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__m_axis_tdata), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("m_axis_tkeep", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__m_axis_tkeep), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("m_axis_tlast", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__m_axis_tlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("m_axis_tready", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__m_axis_tready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("m_axis_tvalid", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__m_axis_tvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("rst_n", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("s_axis_tdata", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__s_axis_tdata), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("s_axis_tkeep", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__s_axis_tkeep), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("s_axis_tlast", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__s_axis_tlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("s_axis_tready", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__s_axis_tready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("s_axis_tvalid", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__s_axis_tvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("state", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("state_next", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__state_next), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("udp_dport", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__udp_dport), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_hft_pipeline_top__u_filter->varInsert("udp_dport_ok", &(TOP.hft_pipeline_top__DOT__u_filter__DOT__udp_dport_ok), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("CNT_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_framer__DOT__CNT_W))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("HEADER_BYTES", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_framer__DOT__HEADER_BYTES))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("KEEP_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_framer__DOT__KEEP_W))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("OFFSET", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_framer__DOT__OFFSET))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("REMAIN", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_framer__DOT__REMAIN))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("SKIP_BEATS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_framer__DOT__SKIP_BEATS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("beat_cnt_r", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__beat_cnt_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("clk", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("combined_data", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__combined_data), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("combined_keep", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__combined_keep), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("m_axis_tdata", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__m_axis_tdata), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("m_axis_tkeep", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__m_axis_tkeep), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("m_axis_tlast", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__m_axis_tlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("m_axis_tready", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__m_axis_tready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("m_axis_tvalid", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__m_axis_tvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("prev_data_r", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__prev_data_r), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("prev_keep_r", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__prev_keep_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("prev_last_r", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__prev_last_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("rst_n", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("s_axis_tdata", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__s_axis_tdata), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("s_axis_tkeep", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__s_axis_tkeep), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("s_axis_tlast", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__s_axis_tlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("s_axis_tready", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__s_axis_tready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("s_axis_tvalid", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__s_axis_tvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("state_next", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__state_next), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_hft_pipeline_top__u_framer->varInsert("state_r", &(TOP.hft_pipeline_top__DOT__u_framer__DOT__state_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("AW", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__AW))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("FRAC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__FRAC))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("IDX_SYM", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__IDX_SYM))), true, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,8,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("N_COMPONENTS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__N_COMPONENTS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("SYMW", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__SYMW))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("WW", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__WW))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("abs_spread", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__abs_spread), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("actual_mid", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__actual_mid), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("actual_q", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__actual_q), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("clk", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("in_tob", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__in_tob), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,137,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("index_accum", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__index_accum), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("next_accum", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__next_accum), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("next_actual", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__next_actual), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("old_mid", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__old_mid), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,499 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("out_index", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__out_index), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("out_trade", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__out_trade), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,161,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("rst_n", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s0_delta", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_delta), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,32,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s0_is_component", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_is_component), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s0_is_index", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_is_index), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s0_new_mid", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_new_mid), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s0_sym", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_sym), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,8,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s0_two_sided", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_two_sided), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s0_valid", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s0_weight", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s0_weight), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s1_delta", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_delta), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,32,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s1_is_component", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_is_component), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s1_is_index", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_is_index), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s1_new_mid", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_new_mid), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s1_sym", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_sym), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,8,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s1_valid", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("s1_weight", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__s1_weight), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("spread", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__spread), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("threshold", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__threshold), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("trade_dir", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__trade_dir), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("trade_fire", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__trade_fire), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("weight_tbl", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__weight_tbl), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,499 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("weighted_delta", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__weighted_delta), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("wt_wr_addr", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__wt_wr_addr), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,8,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("wt_wr_data", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__wt_wr_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb->varInsert("wt_wr_en", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__wt_wr_en), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_index_arb__unnamedblk1->varInsert("i", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_index_arb__unnamedblk2->varInsert("i", &(TOP.hft_pipeline_top__DOT__u_index_arb__DOT__unnamedblk2__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("KEY_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__KEY_W))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("MAX_CHAIN", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__MAX_CHAIN))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("N_WAYS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__N_WAYS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("P_HI", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__P_HI))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("P_LO", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__P_LO))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("Q_HI", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__Q_HI))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("Q_LO", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__Q_LO))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("S_BIT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__S_BIT))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("TBL_ENTRIES", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__TBL_ENTRIES))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("VALUE_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__VALUE_W))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("clk", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("exec_remaining", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__exec_remaining), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_del_done", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_del_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_key), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_del_not_found", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_not_found), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_del_ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_del_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_del_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_ins_done", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_ins_fail", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_fail), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_ins_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_key), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_ins_ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_ins_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_ins_value", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ins_value), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,64,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_lu_hit", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_lu_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_key), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_lu_result_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_result_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_lu_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_lu_value", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_lu_value), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,64,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ht_ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ht_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("lu_hit_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__lu_hit_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("lu_price_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__lu_price_r), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("lu_qty_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__lu_qty_r), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("lu_side_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__lu_side_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("msg_in", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__msg_in), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,300,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("msg_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__msg_r), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,300,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("out", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__out), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,401,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("repl_pending_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__repl_pending_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("rst_n", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("state_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__state_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("wr_key_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__wr_key_r), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_order_lookup->varInsert("wr_val_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__wr_val_r), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,64,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("CHN_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__CHN_W))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("ENTRY_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__ENTRY_W))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("HASH_ROT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_ROT))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 1, 1 ,0,7 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("HASH_SEEDS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__HASH_SEEDS))), true, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,7 ,63,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("IDX_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__IDX_W))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("KEY_HI", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__KEY_HI))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("KEY_LO", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__KEY_LO))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("KEY_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__KEY_W))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("MAX_CHAIN", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__MAX_CHAIN))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("N_WAYS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__N_WAYS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("TBL_ENTRIES", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__TBL_ENTRIES))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("VALUE_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__VALUE_W))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("VAL_HI", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__VAL_HI))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("VAL_LO", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__VAL_LO))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("V_BIT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__V_BIT))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("WAY_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__WAY_W))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("bram_addr_a", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_addr_a), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,11,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("bram_addr_b", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_addr_b), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,11,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("bram_rdata_a", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_a), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,129,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("bram_rdata_b", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_rdata_b), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,129,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("bram_wdata_b", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_wdata_b), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,3 ,129,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("bram_wen_b", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__bram_wen_b), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 1, 0 ,0,3);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("chain_cnt_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__chain_cnt_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("clear_addr_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__clear_addr_r), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,11,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("clk", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("cmp_found_empty", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__cmp_found_empty), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("cmp_found_existing", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__cmp_found_existing), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("cmp_sel_idx", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__cmp_sel_idx), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,11,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("cmp_sel_way", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__cmp_sel_way), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("delete_done", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("delete_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_key), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("delete_not_found", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_not_found), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("delete_ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("delete_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__delete_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("evict_dst_idx_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_dst_idx_r), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,11,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("evict_dst_way_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_dst_way_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("evict_key_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_key_r), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("evict_slot_empty", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_slot_empty), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("evict_value_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__evict_value_r), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,64,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("insert_done", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("insert_fail", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_fail), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("insert_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_key), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("insert_ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("insert_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("insert_value", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__insert_value), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,64,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("lookup_hit", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("lookup_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_key), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("lookup_result_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_result_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("lookup_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("lookup_value", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__lookup_value), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,64,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("needs_evict_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__needs_evict_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("op_is_insert_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__op_is_insert_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("op_key_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__op_key_r), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("op_value_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__op_value_r), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,64,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("ready", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__ready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("rst_n", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("s1_hit", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__s1_hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("s1_key", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__s1_key), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("s1_valid", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__s1_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("s1_value", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__s1_value), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,64,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("sel_idx_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__sel_idx_r), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,11,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("sel_way_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__sel_way_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table->varInsert("state_r", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__state_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__0__KET__->varInsert("mem", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__gen_bram__BRA__0__KET____DOT__mem), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,4095 ,129,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__1__KET__->varInsert("mem", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__gen_bram__BRA__1__KET____DOT__mem), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,4095 ,129,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__2__KET__->varInsert("mem", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__gen_bram__BRA__2__KET____DOT__mem), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,4095 ,129,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__3__KET__->varInsert("mem", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__gen_bram__BRA__3__KET____DOT__mem), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,4095 ,129,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk3->varInsert("w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk3__DOT__w), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk4->varInsert("w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk4__DOT__w), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk5->varInsert("w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk5__DOT__w), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk6->varInsert("w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk6__DOT__w), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk7->varInsert("w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk7__DOT__w), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk8->varInsert("w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk8__DOT__w), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk9->varInsert("w", &(TOP.hft_pipeline_top__DOT__u_order_lookup__DOT__u_order_table__DOT__unnamedblk9__DOT__w), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("N_LEVELS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tob__DOT__N_LEVELS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("N_SYMBOLS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tob__DOT__N_SYMBOLS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("SYM_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tob__DOT__SYM_W))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("add_inserted", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__add_inserted), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("add_match_found", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__add_match_found), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("add_price", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__add_price), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("add_qty", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__add_qty), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("after_add", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__after_add), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,2 ,63,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("after_rm", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__after_rm), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,2 ,63,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("ask_book", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__ask_book), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 2, 1 ,0,499 ,0,2 ,63,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("better_than", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__better_than), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("bid_book", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__bid_book), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 2, 1 ,0,499 ,0,2 ,63,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("clk", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("cur", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__cur), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,2 ,63,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("do_add", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__do_add), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("do_remove", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__do_remove), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("in_update", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__in_update), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,401,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("is_bid", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__is_bid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("msg_type", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__msg_type), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,2,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("op_side", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__op_side), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("out_tob", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__out_tob), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,137,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("rm_found", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__rm_found), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("rm_price", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__rm_price), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("rm_qty", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__rm_qty), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("rst_n", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("sym", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__sym), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,8,0);
    __Vscopep_hft_pipeline_top__u_tob->varInsert("sym_valid", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__sym_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk1->varInsert("i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk10->varInsert("s", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk10__DOT__s), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk10__unnamedblk11->varInsert("l", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk10__DOT__unnamedblk11__DOT__l), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk12->varInsert("l", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk12__DOT__l), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk13->varInsert("l", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk13__DOT__l), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk2->varInsert("i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk2__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk3->varInsert("i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk3__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk3__unnamedblk4->varInsert("j", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk3__DOT__unnamedblk4__DOT__j), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk5->varInsert("i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk5__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk6->varInsert("i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk6__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk7->varInsert("i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk7__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk8->varInsert("i", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk8__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tob__unnamedblk8__unnamedblk9->varInsert("j", &(TOP.hft_pipeline_top__DOT__u_tob__DOT__unnamedblk8__DOT__unnamedblk9__DOT__j), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("BEAT_W", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__BEAT_W))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("COOLDOWN_CYC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__COOLDOWN_CYC))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("DST_IP", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__DST_IP))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("DST_MAC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__DST_MAC))), true, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,47,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("DST_PORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__DST_PORT))), true, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("IDX_SYM_ID", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__IDX_SYM_ID))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("IP_CSUM", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__IP_CSUM))), true, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("IP_TOTAL_LEN", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__IP_TOTAL_LEN))), true, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("LAST_BEAT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__LAST_BEAT))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("MAX_POS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__MAX_POS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("N_BEATS", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__N_BEATS))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("ORDER_MSG_NEW", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__ORDER_MSG_NEW))), true, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("ORDER_QTY", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__ORDER_QTY))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("PRICE_OFFSET", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__PRICE_OFFSET))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("SRC_IP", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__SRC_IP))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("SRC_MAC", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__SRC_MAC))), true, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,47,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("SRC_PORT", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__SRC_PORT))), true, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("UDP_LEN", const_cast<void*>(static_cast<const void*>(&(TOP.hft_pipeline_top__DOT__u_tx__DOT__UDP_LEN))), true, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,15,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("beat_data", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__beat_data), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("beat_keep", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__beat_keep), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("beat_last", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__beat_last), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("beat_r", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__beat_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("cd_cnt", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__cd_cnt), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("cd_ok", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__cd_ok), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("clk", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("enable", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("in_trade", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__in_trade), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,161,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("lat_dir", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__lat_dir), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("lat_oid", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__lat_oid), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("lat_price", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__lat_price), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("lat_spread", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__lat_spread), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("m_axis_tdata", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__m_axis_tdata), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("m_axis_tkeep", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__m_axis_tkeep), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("m_axis_tlast", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__m_axis_tlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("m_axis_tready", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__m_axis_tready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("m_axis_tvalid", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__m_axis_tvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("net_position", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__net_position), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("next_pos", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__next_pos), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("oid_seq", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__oid_seq), false, VLVT_UINT64, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,63,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("order_count", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__order_count), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("pkt_sent", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__pkt_sent), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("pos_ok", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__pos_ok), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("rst_n", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_hft_pipeline_top__u_tx->varInsert("state_r", &(TOP.hft_pipeline_top__DOT__u_tx__DOT__state_r), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,0,0);
}

Vtop__Syms::~Vtop__Syms() {
    // Tear down scope hierarchy
    __Vhier.remove(0, __Vscopep_hft_pipeline_top);
    __Vhier.remove(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_demux);
    __Vhier.remove(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_filter);
    __Vhier.remove(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_framer);
    __Vhier.remove(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_index_arb);
    __Vhier.remove(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_order_lookup);
    __Vhier.remove(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_tob);
    __Vhier.remove(__Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top__u_tx);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_index_arb, __Vscopep_hft_pipeline_top__u_index_arb__unnamedblk1);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_index_arb, __Vscopep_hft_pipeline_top__u_index_arb__unnamedblk2);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_order_lookup, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__0__KET__);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__1__KET__);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__2__KET__);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__3__KET__);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk3);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk4);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk5);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk6);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk7);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk8);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk9);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk1);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk10);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk12);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk13);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk2);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk3);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk5);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk6);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk7);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob__unnamedblk8);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob__unnamedblk10, __Vscopep_hft_pipeline_top__u_tob__unnamedblk10__unnamedblk11);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob__unnamedblk3, __Vscopep_hft_pipeline_top__u_tob__unnamedblk3__unnamedblk4);
    __Vhier.remove(__Vscopep_hft_pipeline_top__u_tob__unnamedblk8, __Vscopep_hft_pipeline_top__u_tob__unnamedblk8__unnamedblk9);
    // Clear keys from hierarchy map after values have been removed
    __Vhier.clear();
    // Tear down scopes
    VL_DO_CLEAR(delete __Vscopep_TOP, __Vscopep_TOP = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top, __Vscopep_hft_pipeline_top = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_demux, __Vscopep_hft_pipeline_top__u_demux = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_filter, __Vscopep_hft_pipeline_top__u_filter = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_framer, __Vscopep_hft_pipeline_top__u_framer = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_index_arb, __Vscopep_hft_pipeline_top__u_index_arb = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_index_arb__unnamedblk1, __Vscopep_hft_pipeline_top__u_index_arb__unnamedblk1 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_index_arb__unnamedblk2, __Vscopep_hft_pipeline_top__u_index_arb__unnamedblk2 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup, __Vscopep_hft_pipeline_top__u_order_lookup = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__0__KET__, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__0__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__1__KET__, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__1__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__2__KET__, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__2__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__3__KET__, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__gen_bram__BRA__3__KET__ = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk3, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk3 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk4, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk4 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk5, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk5 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk6, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk6 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk7, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk7 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk8, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk8 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk9, __Vscopep_hft_pipeline_top__u_order_lookup__u_order_table__unnamedblk9 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob, __Vscopep_hft_pipeline_top__u_tob = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk1, __Vscopep_hft_pipeline_top__u_tob__unnamedblk1 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk10, __Vscopep_hft_pipeline_top__u_tob__unnamedblk10 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk10__unnamedblk11, __Vscopep_hft_pipeline_top__u_tob__unnamedblk10__unnamedblk11 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk12, __Vscopep_hft_pipeline_top__u_tob__unnamedblk12 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk13, __Vscopep_hft_pipeline_top__u_tob__unnamedblk13 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk2, __Vscopep_hft_pipeline_top__u_tob__unnamedblk2 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk3, __Vscopep_hft_pipeline_top__u_tob__unnamedblk3 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk3__unnamedblk4, __Vscopep_hft_pipeline_top__u_tob__unnamedblk3__unnamedblk4 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk5, __Vscopep_hft_pipeline_top__u_tob__unnamedblk5 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk6, __Vscopep_hft_pipeline_top__u_tob__unnamedblk6 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk7, __Vscopep_hft_pipeline_top__u_tob__unnamedblk7 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk8, __Vscopep_hft_pipeline_top__u_tob__unnamedblk8 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tob__unnamedblk8__unnamedblk9, __Vscopep_hft_pipeline_top__u_tob__unnamedblk8__unnamedblk9 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_hft_pipeline_top__u_tx, __Vscopep_hft_pipeline_top__u_tx = nullptr);
    // Tear down sub module instances
}
